### DISCUSSION TITLE
Portainer repeatedly showing error

### DISCUSSION THREAD

**Discussion by bma73-bma** [wollomatic/socket-proxy#38] [Q&A]
Hi,

I'm trying this out with a Portainer container and it looks like everything is working, I can access Portainer and see the containers etc. But when I look in the Portainer container log file I see this repeated warning:

`WRN github.com/portainer/portainer/api/platform/platform.go:70 > failed to retrieve docker info | error="Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?"`

My docker-compose.yml:
```
services:
  # Docker Socket Proxy - Security Enchanced Proxy for Docker Socket
  socket-proxy:
    container_name: socket-proxy
    image: wollomatic/socket-proxy:1
    restart: unless-stopped
    user: "65534:988"
    mem_limit: 64M
    read_only: true
    cap_drop:
    - ALL
    security_opt:
    - no-new-privileges
    command:
    - '-loglevel=debug'
    - '-listenip=0.0.0.0'
    - '-allowfrom=portainer'
    #- '-allowGET=/v1\..{1,2}/(version|containers/.*|events.*)'
    - '-allowGET=.*'
    - '-allowHEAD=.*'
    - '-allowPOST=.*'
    - '-allowPUT=.*'
    - '-allowPATCH=.*'
    - '-allowDELETE=.*'
    - '-allowCONNECT=.*'
    - '-allowTRACE=.*'
    - '-allowOPTIONS=.*'
    - '-watchdoginterval=3600'
    - '-stoponwatchdog'
    - '-shutdowngracetime=5'
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      socket_proxy:

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest # Use portainer-ce if you do no have a Business Edition license key
    security_opt:
    - no-new-privileges:true
    restart: unless-stopped
    networks:
    - default
    - socket_proxy
    command: -H tcp://socket-proxy:2375
    ports:
    - "9000:9000"
    volumes:
    - /home/ubuntu/docker/appdata/portainer/data:/data # Change to local directory if you want to save/transfer config locally
    environment:
    - TZ='Europe/Stockholm'
    depends_on:
      - socket-proxy

networks:
  default:
    driver: bridge
  socket_proxy:
    name: socket_proxy
    driver: bridge
    internal: true
```

I allow all using the `=.*` because I want to figure out how to write the correct regexp needed. I don't really understand those expressions yet :)

Is this warning something to care about or should I just ignore it?
