### ISSUE TITLE
Option -stoponwatchdog not recognising docker proxy failure

### ISSUE THREAD

**Issue by ogmueller** [wollomatic/socket-proxy#23]
**Describe the bug**

I am using ubuntu 22.04 with docker v27.0.3 [build 7d4bcd8] and latest docker-proxy v1.3.4. When we update docker, it might happen, that the socket vanishes for some time. I am using the `-stoponwatchdog` feature, but it will not detect that situation for days.

Here is a log example of it:
```
docker-proxy  | 2024/07/24 22:32:54 cron: panic running job: runtime error: invalid memory address or nil pointer dereference
docker-proxy  | goroutine 233 [running]:
docker-proxy  | github.com/robfig/cron.(*Cron).runWithRecovery.func1()
docker-proxy  | 	/home/runner/go/pkg/mod/github.com/robfig/cron@v1.2.0/cron.go:161 +0x69
docker-proxy  | panic({0xaad020, 0x10b18e0})
docker-proxy  | 	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:838 +0x207
docker-proxy  | github.com/containrrr/watchtower/pkg/metrics.NewMetric({0x0, 0x0})
docker-proxy  | 	/home/runner/work/watchtower/watchtower/pkg/metrics/metrics.go:31 +0x22
docker-proxy  | github.com/containrrr/watchtower/cmd.runUpdatesWithNotifications(0xc00039f4e0)
docker-proxy  | 	/home/runner/work/watchtower/watchtower/cmd/root.go:377 +0x171
docker-proxy  | github.com/containrrr/watchtower/cmd.runUpgradesOnSchedule.func1()
docker-proxy  | 	/home/runner/work/watchtower/watchtower/cmd/root.go:325 +0xd2
docker-proxy  | github.com/robfig/cron.FuncJob.Run(0xc000355fd0?)
docker-proxy  | 	/home/runner/go/pkg/mod/github.com/robfig/cron@v1.2.0/cron.go:92 +0x1a
docker-proxy  | github.com/robfig/cron.(*Cron).runWithRecovery(0x5692f6?, {0xc7e060?, 0xc0001b61e0?})
docker-proxy  | 	/home/runner/go/pkg/mod/github.com/robfig/cron@v1.2.0/cron.go:165 +0x62
docker-proxy  | created by github.com/robfig/cron.(*Cron).run
docker-proxy  | 	/home/runner/go/pkg/mod/github.com/robfig/cron@v1.2.0/cron.go:199 +0x79f
```

**To Reproduce**
Set the following compose settings:
```yaml
    image: wollomatic/socket-proxy:1
    restart: unless-stopped
    user: "65534:998"
    read_only: true
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges
    command:
      - '-loglevel=info'
      - '-allowhealthcheck'
      - '-allowfrom=0.0.0.0/0'
      - '-listenip=0.0.0.0'
      - '-allowGET=/v[0-9.]+/(containers|images)/.*'
      - '-allowPOST=/v[0-9.]+/(containers|images|networks)/.*'
      - '-allowDELETE=/v[0-9.]+/(containers|images|networks)/.*'
      - '-allowHEAD=.*'
      - '-watchdoginterval=30' # check for socket availability
      - '-stoponwatchdog' # halt program on error and let compose restart it
      - '-shutdowngracetime=5' # wait 5 seconds before shutting down
    healthcheck:
      test: ["CMD", "./healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 2
```
and update docker. When another docker container is using this proxy, the error message appears.

**Expected behavior**
I would expect that the socker-proxy detects the problem with the docker socket, kills the process and let docker restart the container again.

**Comment by wollomatic** [comment]
Thanks for reaching out. Updating docker was indeed the reason I added the watchdog. I use a similar configuration and it works.

Could You please set the loglevel to debug? Then every watchdog action should be logged.

I'll try to reproduce the issue later. There's a docker update waiting on my test server anyway.

**Comment by wollomatic** [comment]
How's your docker daemon configured? Do you have live-restore enbled?

**Comment by ogmueller** [comment]
yes, live restore is active:
```
    "live-restore": true,
```

**Comment by wollomatic** [comment]
Here it works like it should:
```
dockerproxy-1  | time=2024-07-25T11:32:24.859Z level=DEBUG msg="checking socket availability" origin=checkSocketAvailability
dockerproxy-1  | time=2024-07-25T11:32:52.106Z level=INFO msg="httputil: ReverseProxy read error during body copy: unexpected EOF"
dockerproxy-1  | time=2024-07-25T11:32:54.860Z level=DEBUG msg="checking socket availability" origin=checkSocketAvailability
dockerproxy-1  | time=2024-07-25T11:32:54.860Z level=ERROR msg="socket is unavailable" origin=watchdog error="dial unix /var/run/docker.sock: connect: connection refused"
dockerproxy-1  | time=2024-07-25T11:32:54.860Z level=WARN msg="stopping socket-proxy because of unavailable socket" origin=watchdog
dockerproxy-1  | time=2024-07-25T11:33:00.079Z level=INFO msg="starting socket-proxy" version=1.3.4 os=linux arch=amd64 runtime=go1.22.5 URL=github.com/wollomatic/socket-proxy
```
Line 1 - successful check
Line 2 - problem occured due to Docker update
Line 3 - watchdog check
Line 4 - watchdog detects connectivity error
Line 5 - socket-proxy exits due to unsuccessful watchdog check
Line 6 - socket-proxy is restarted by Docker

That's my configuration:
```
  dockerproxy:
    image: wollomatic/socket-proxy:1.3.4
    restart: unless-stopped
    user: "65534:998"
    mem_limit: 64M
    read_only: true
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges
    command:
#      - '-loglevel=info'
      - '-loglevel=debug'
      - '-listenip=0.0.0.0'
      - '-allowfrom=traefik'
      - '-allowGET=/v1\..{1,2}/(version|containers/.*|events.*)'
#      - '-watchdoginterval=300'
      - '-watchdoginterval=30'
      - '-stoponwatchdog'
      - '-shutdowngracetime=5'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - docker-proxynet
```

I'm not really sure where your log excerpt in the first post comes from - I guess that's the output of Watchtower and not socker-proxy?

**Comment by ogmueller** [comment]
It is the log output of docker-proxy, but yes watchtower was using it.

**Comment by wollomatic** [comment]
This is weird, because socket-proxy does not use any external dependency like robfig/cron.

Also, any panic would terminate socket-proxy and lead to be restarted be Docker. 

Could you please give me a bit more context of the log, or the complete compose file?

If you don't want to share it in public, feel free to send it to me via email <github@wollomatic.de>

**Comment by ogmueller** [comment]
This is our compose file for the docker-proxy itself:

```yaml
---
services:
  docker-proxy-watchtower:
    container_name: ${COMPOSE_PROJECT_NAME}-watchtower
    image: wollomatic/socket-proxy:1
    restart: unless-stopped
    user: "65534:998"
    read_only: true
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges
    command:
      - '-loglevel=debug'
      - '-allowhealthcheck'
      - '-allowfrom=0.0.0.0/0'
      - '-listenip=0.0.0.0'
      - '-allowGET=/v[0-9.]+/(containers|images)/.*'
      - '-allowPOST=/v[0-9.]+/(containers|images|networks)/.*'
      - '-allowDELETE=/v[0-9.]+/(containers|images|networks)/.*'
      - '-allowHEAD=.*'
      - '-watchdoginterval=30' # check for socket availability
      - '-stoponwatchdog' # halt program on error and let compose restart it
      - '-shutdowngracetime=5' # wait 5 seconds before shutting down
    healthcheck:
      test: ["CMD", "./healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 2

    labels:
      # watchtower
      - "com.centurylinklabs.watchtower.enable=true"
      - "com.centurylinklabs.watchtower.scope=${COMPOSE_PROJECT_NAME}"

    networks:
      - docker-proxy_global

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    deploy:
      resources:
          limits:
              memory: 64M


  watchtower:
    container_name: ${COMPOSE_PROJECT_NAME}-watchtower-app
    image: containrrr/watchtower:latest
    restart: unless-stopped

    depends_on:
      - docker-proxy-watchtower

    environment:
      TZ: Europe/Berlin
      DOCKER_HOST: tcp://docker-proxy-watchtower:2375
      WATCHTOWER_NO_STARTUP_MESSAGE: "true"
      WATCHTOWER_SCOPE: "${COMPOSE_PROJECT_NAME}"
      WATCHTOWER_LABEL_ENABLE: "true"
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_TIMEOUT: 30s

    labels:
      # Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
      - "com.centurylinklabs.watchtower.scope=${COMPOSE_PROJECT_NAME}"

    networks:
      - docker-proxy_global

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

    deploy:
      resources:
        limits:
          memory: 64M


networks:
  docker-proxy_global:
    external: true


# vim: syntax=yaml ts=2 sw=2 et sr softtabstop=2 autoindent
```

and this is another compose file in part, which is using this proxy for watchtower:

```yaml
---

services:
  app:
    image: lukevella/rallly
    restart: unless-stopped
    depends_on:
      - postgres

    env_file:
      - .env

    networks:
      - default
      - traefik_global

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`some.app.com`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls.certresolver=letsencrypt_prod"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.middlewares=hsts-header@file"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.service=app-${COMPOSE_PROJECT_NAME}"
      - "traefik.http.services.app-${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=3000"

      # watchtower
      - "com.centurylinklabs.watchtower.enable=true"
      - "com.centurylinklabs.watchtower.scope=${COMPOSE_PROJECT_NAME}"

    deploy:
      resources:
        limits:
          memory: 512M

  postgres:
    image: postgres:16
    restart: always
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

    environment:
      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

    labels:
      # watchtower
      - "com.centurylinklabs.watchtower.enable=true"
      - "com.centurylinklabs.watchtower.scope=${COMPOSE_PROJECT_NAME}"

    deploy:
      resources:
        limits:
          memory: 256M

  watchtower:
    container_name: ${COMPOSE_PROJECT_NAME}-watchtower
    image: containrrr/watchtower:latest
    restart: unless-stopped

    environment:
      TZ: Europe/Berlin
      DOCKER_HOST: tcp://docker-proxy-watchtower:2375
      WATCHTOWER_NO_STARTUP_MESSAGE: "true"
      WATCHTOWER_SCOPE: "${COMPOSE_PROJECT_NAME}"
      WATCHTOWER_LABEL_ENABLE: "true"
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_TIMEOUT: 30s

    labels:
      # watchtower
      - "com.centurylinklabs.watchtower.enable=true"
      - "com.centurylinklabs.watchtower.scope=${COMPOSE_PROJECT_NAME}"

    networks:
      - docker-proxy_global

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

    deploy:
      resources:
        limits:
          memory: 48M


networks:
  docker-proxy_global:
    external: true
  traefik_global:
    external: true


# vim: syntax=yaml ts=2 sw=2 et sr softtabstop=2 autoindent
```
