### ISSUE TITLE
It works with Docker swarm ?

### ISSUE THREAD

**Issue by D0wn3r** [wollomatic/socket-proxy#32]
Do this works with docker swarm ?

I have a
```
level=WARN msg="blocked request" reason="forbidden IP" method=GET URL=/v1.24/version client=10.0.2.67:60802 response=403
```
When I try to use it with Traefik v3. I guess this is supposed to be allowed with the option `-allowfrom=reverse-proxy` in the command but with swarm is that works ?

(`reverse-proxy` in the name of my traefik service in the stack)

Thanks

**Comment by D0wn3r** [comment]
It works if I set ip (but I would like it dynamic) and if I allow all GET
```
services:
  dockerproxy:
    image: wollomatic/socket-proxy:1 # see https://github.com/wollomatic/socket-proxy for reference
    command:
      - '-loglevel=info' # set to debug for far more logging
      - '-allowfrom=10.0.2.67,10.0.2.68,10.0.2.62'
      - '-listenip=0.0.0.0'
      - '-allowGET=.*' # this regexp allows readonly access only for requests that traefik needs
      - '-shutdowngracetime=5'
      - '-watchdoginterval=600'
      - '-stoponwatchdog'
 ```
